topics:
  source: konihwes-input
  sink: konihwes-output

spring:
  application.name: detect
  kafka:
    client-id: ${spring.application.name}
    bootstrap-servers: dory.srvs.cloudkafka.com:9094
    consumer:
      auto-offset-reset: earliest
      group-id: konihwes-${spring.application.name}
    properties:
      "security.protocol": SASL_SSL
      "sasl.mechanism": SCRAM-SHA-512
      "sasl.jaas.config": org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
